# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quasar < Formula
  desc "Astral themed agent orchestration system inspired by Gas Town"
  homepage "https://github.com/papapumpkin/quasar"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/papapumpkin/quasar/releases/download/v0.1.0/quasar_0.1.0_darwin_amd64.tar.gz"
      sha256 "ff6c70d84388dddde7be986c51c6eb771fe0a90475788b8df75fed9456d0a577"

      define_method(:install) do
        bin.install "quasar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/papapumpkin/quasar/releases/download/v0.1.0/quasar_0.1.0_darwin_arm64.tar.gz"
      sha256 "6b03bbb2fb688a608f707ade6c77d528ce5c8ef8f329794cddde7f18fc20e2dd"

      define_method(:install) do
        bin.install "quasar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/papapumpkin/quasar/releases/download/v0.1.0/quasar_0.1.0_linux_amd64.tar.gz"
      sha256 "9a5f15fd49832222e94f4c0bfd0604616ce67499d3e51430b2d05fd8b95d029b"
      define_method(:install) do
        bin.install "quasar"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quasar version")
  end
end
