# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quasar < Formula
  desc "Astral themed agent orchestration system inspired by Gas Town"
  homepage "https://github.com/papapumpkin/quasar"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/papapumpkin/quasar/releases/download/v0.1.1/quasar_0.1.1_darwin_amd64.tar.gz"
      sha256 "b8337e4650747efcf6cc8259c5a662e79515b036c566a92e9bbe260314afa6e2"

      define_method(:install) do
        bin.install "quasar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/papapumpkin/quasar/releases/download/v0.1.1/quasar_0.1.1_darwin_arm64.tar.gz"
      sha256 "db33d5e44c99ac4d0ef4676823791728953e9069e7ee09940a7510c1ed4be9f2"

      define_method(:install) do
        bin.install "quasar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/papapumpkin/quasar/releases/download/v0.1.1/quasar_0.1.1_linux_amd64.tar.gz"
      sha256 "51d514fdeeb1f0cd294c65354e54a3773e306e19ce1f8ca1ed6172f88776d7d8"
      define_method(:install) do
        bin.install "quasar"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quasar version")
  end
end
